server {
    listen 80;

    location / {
        proxy_pass http://cms:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /dba/ {
        proxy_pass http://dba:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}